In [1]:
# download data-profiling
!pip install fg-data-profiling

Requirement already satisfied: fg-data-profiling in /usr/local/lib/python3.12/dist-packages (4.19.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from fg-data-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)

In [2]:
#import libraries
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

In [3]:
# upload a file to google colab
upoloaed = files.upload()

Saving Dataset for Data Analytics - Sheet1.csv to Dataset for Data Analytics - Sheet1 (2).csv

In [4]:
#Convert file to dataframe for analysis using pandas
df = pd.read_csv("Dataset for Data Analytics - Sheet1.csv")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [5]:
#My first try using data profiling
profile = ProfileReport(df,title="Profiling Report", explorative=True)
profile.to_file("report.html")
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 21%|██▏       | 3/14 [00:00<00:00, 21.33it/s]
100%|██████████| 14/14 [00:00<00:00, 37.52it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
#Explorative data analysis
df.shape

(1200, 14)

In [7]:
#checking data types
df.dtypes

OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

In [8]:
#Checking for missing values
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [9]:
#The Dataset has 1200 rows and 14 columns
#Only one column has missing values and it is a category column

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [11]:
#Checking for the types of values in the column with missing values and the
# number of unique values
df['CouponCode'].unique()
df['CouponCode'].nunique()

3

In [12]:
#Standardising the column names by turning all to lower case and removing whitespaces
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
)

In [14]:
# the column couponcode has 25.75% of empyt rows
missing = df.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

couponcode    25.75
dtype: float64

In [15]:
df.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [16]:
#Showed the data sets had no duplicates
n_dupes = df.duplicated().sum()
print(n_dupes)

0

In [17]:
#fill empty rows of the couponcode column with unkown
df['couponcode'] = df['couponcode'].fillna('unknown')
df['couponcode'].unique()

array(['SAVE10', 'FREESHIP', 'unknown', 'WINTER15'], dtype=object)

In [18]:
#Checking to see if the missing rows have been removed
missing = df.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

Series([], dtype: float64)

In [19]:
print(missing)

orderid            0.0
date               0.0
customerid         0.0
product            0.0
quantity           0.0
unitprice          0.0
shippingaddress    0.0
paymentmethod      0.0
orderstatus        0.0
trackingnumber     0.0
itemsincart        0.0
couponcode         0.0
referralsource     0.0
totalprice         0.0
dtype: float64

In [20]:
#Converting every string on the data frame to lower case and removing whitespaces
df = df.map(lambda x:x.strip().lower() if isinstance(x, str) else x)
df.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ord200000,2023-01-04,c72649,monitor,5,570.62,928 main st,debit card,shipped,trk37947903,7,save10,instagram,2853.10
1,ord200001,2024-08-23,c75739,phone,2,151.35,823 main st,online,shipped,trk91186779,3,save10,referral,302.70
2,ord200002,2024-02-27,c81728,tablet,5,550.68,512 main st,credit card,cancelled,trk42903982,8,freeship,email,2753.40
3,ord200003,2023-10-15,c33540,chair,1,273.19,275 main st,debit card,returned,trk62788070,5,save10,facebook,273.19
4,ord200004,2025-05-08,c81840,printer,4,626.01,668 main st,online,delivered,trk29241424,8,save10,email,2504.04

In [21]:
#Changing the date column from object to date time
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ord200000,2023-01-04,c72649,monitor,5,570.62,928 main st,debit card,shipped,trk37947903,7,save10,instagram,2853.10
1,ord200001,2024-08-23,c75739,phone,2,151.35,823 main st,online,shipped,trk91186779,3,save10,referral,302.70
2,ord200002,2024-02-27,c81728,tablet,5,550.68,512 main st,credit card,cancelled,trk42903982,8,freeship,email,2753.40
3,ord200003,2023-10-15,c33540,chair,1,273.19,275 main st,debit card,returned,trk62788070,5,save10,facebook,273.19
4,ord200004,2025-05-08,c81840,printer,4,626.01,668 main st,online,delivered,trk29241424,8,save10,email,2504.04

In [22]:
#Checking to see if the change worked
df.dtypes

orderid                    object
date               datetime64[ns]
customerid                 object
product                    object
quantity                    int64
unitprice                 float64
shippingaddress            object
paymentmethod              object
orderstatus                object
trackingnumber             object
itemsincart                 int64
couponcode                 object
referralsource             object
totalprice                float64
dtype: object

In [23]:
#Rounding up all float columns to 2 decimal places
float_cols = df.select_dtypes(include='float').columns
df[float_cols] = df[float_cols].round(2)
df.head()

,orderid,date,customerid,product,quantity,unitprice,shippingaddress,paymentmethod,orderstatus,trackingnumber,itemsincart,couponcode,referralsource,totalprice
0,ord200000,2023-01-04,c72649,monitor,5,570.62,928 main st,debit card,shipped,trk37947903,7,save10,instagram,2853.10
1,ord200001,2024-08-23,c75739,phone,2,151.35,823 main st,online,shipped,trk91186779,3,save10,referral,302.70
2,ord200002,2024-02-27,c81728,tablet,5,550.68,512 main st,credit card,cancelled,trk42903982,8,freeship,email,2753.40
3,ord200003,2023-10-15,c33540,chair,1,273.19,275 main st,debit card,returned,trk62788070,5,save10,facebook,273.19
4,ord200004,2025-05-08,c81840,printer,4,626.01,668 main st,online,delivered,trk29241424,8,save10,email,2504.04

In [24]:
df.shape

(1200, 14)

In [27]:
#I want to see my profile report after analysing
profile2 = ProfileReport(df,title="Profiling Report2", explorative=True)
profile2.to_file("report2.html")
files.download('report2.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 36%|███▌      | 5/14 [00:00<00:00, 42.26it/s]
100%|██████████| 14/14 [00:00<00:00, 45.16it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [26]:
#converting dataframe back to an excel file
df.to_excel('project1_cleaned.xlsx', index=False)
from google.colab import files
files.download('project1_cleaned.xlsx')